### ISSUE TITLE
Cannot import `CustomGoogleScholarTopPublicationCitations`

### ISSUE THREAD

**Issue by rohanjha123** [dimitryzub/scrape-google-scholar-py#13]
I'm currently using a macOS Big Sur, python 3.11.1. While I can import `CustomGoogleScholarOrganic` without issues, I am unable to import CustomGoogleScholarTopPublicationCitations, with the relevant error message included below.

```
>>> from google_scholar_py import CustomGoogleScholarTopPublicationCitations
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ImportError: cannot import name 'CustomGoogleScholarTopPublicationCitations' from 'google_scholar_py' (/Users/rohanjha/.pyenv/versions/3.11.1/lib/python3.11/site-packages/google_scholar_py/__init__.py)
>>> from google_scholar_py import CustomGoogleScholarOrganic
>>> 
```
Any help on this would be greatly appreciated! Additionally, [example_usage.py](https://github.com/dimitryzub/scrape-google-scholar-py/blob/main/example_usage.py) says that documentation exists for each of these functions. Could you please point me to the documentation if possible? I'm interested in scraping the citation counts for various papers, and would love to read up on the best way I can do so. Thanks for your support!

**Comment by rohanjha123** [comment]
Hi, I'd read the thread linked above but I don't believe this is a duplicate because I'm using Python 3.11 and can only not import 1 package (while importing the other 2 works fine)

**Comment by dimitryzub** [comment]
@rohanjha123 I apologize, it was a typo by me. There's no `CustomGoogleScholarTopPublicationCitations` class. [I've updated `example_usage.py`](https://github.com/dimitryzub/scrape-google-scholar-py/commit/04227d0e396180086835dbcb339e795727647589)

Class naming is confusing. This is something I'll update in the future.

Correct code example:

```python
from google_scholar_py import CustomGoogleScholarTopPublicationArticle
import json

top_publication_citation = CustomGoogleScholarTopPublicationArticle().scrape_google_scholar_top_publication_articles(
    journal_publications_link='https://scholar.google.com/citations?hl=en&vq=en&view_op=list_hcore&venue=TdhLrHqKTh8J.2022',
    pagination=True,
    save_to_csv=False,
    save_to_json=False
)

print(json.dumps(top_publication_citation, indent=2, ensure_ascii=False))
```

```diff
- from google_scholar_py import CustomGoogleScholarTopPublicationCitations
+ from google_scholar_py import CustomGoogleScholarTopPublicationArticle
```


Let me know if this works for you.
